name: Build and deploy wasm R package repository
on:
  workflow_dispatch:
  repository_dispatch:
    types: [rebuild]
  push:
    branches: [main, master]
jobs:
  deploy-cran-repo:
    uses: r-wasm/actions/.github/workflows/deploy-cran-repo.yml@v3
    with:
      packages: |
        deSolve
        jackkrebsbach/rwendy
    permissions:
      repository-projects: read
      pages: write
      id-token: write
